//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.WebApplicationAids.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.WebApplicationAids.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applicationSettings.
        /// </summary>
        internal static string APP_SETTINGS_NAME_APP_CONFIG {
            get {
                return ResourceManager.GetString("APP_SETTINGS_NAME_APP_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration.
        /// </summary>
        internal static string APP_SETTINGS_NAME_CONFIGURATION {
            get {
                return ResourceManager.GetString("APP_SETTINGS_NAME_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings.
        /// </summary>
        internal static string APP_SETTINGS_NAME_WEB_CONFIG {
            get {
                return ResourceManager.GetString("APP_SETTINGS_NAME_WEB_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Node {0} of parent node {1} has unexpected attributes named {2} and {3}. The geometry of this configuration file is unsupported..
        /// </summary>
        internal static string ERRMSG_SECTION_UNEXPECTED_GEOMETRY {
            get {
                return ResourceManager.GetString("ERRMSG_SECTION_UNEXPECTED_GEOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;XML Element named {0} of element named {1} has children. Application configurations with great grandchildren are unsupported..
        /// </summary>
        internal static string ERRMSG_SECTIONS_NESTED_TOO_DEEPLY {
            get {
                return ResourceManager.GetString("ERRMSG_SECTIONS_NESTED_TOO_DEEPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In method GetAppSettingsKeysFromAnyConfig, found XML Node named {0} with {1} children..
        /// </summary>
        internal static string TRACEMSG_1 {
            get {
                return ResourceManager.GetString("TRACEMSG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Node {0} of {1}: Name = {2}, Children = {3}, InnerText = {4}.
        /// </summary>
        internal static string TRACEMSG_2 {
            get {
                return ResourceManager.GetString("TRACEMSG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Node {0} of {1}: Type = {2}.
        /// </summary>
        internal static string TRACEMSG_3 {
            get {
                return ResourceManager.GetString("TRACEMSG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Node {0} of {1}: Name = {2}, Children = {3}, Name = {4}, Value = {5}.
        /// </summary>
        internal static string TRACEMSG_4 {
            get {
                return ResourceManager.GetString("TRACEMSG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Node {0} of {1}: Name = {2}, Children = {3}, Attribute0Name = {4}, Attribute1Name = {5}.
        /// </summary>
        internal static string TRACEMSG_5 {
            get {
                return ResourceManager.GetString("TRACEMSG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Node {0} of {1}: Name = {2}, Children = {3}, Actual attribute count = {4}, Expected attribute count = {5}.
        /// </summary>
        internal static string TRACEMSG_6 {
            get {
                return ResourceManager.GetString("TRACEMSG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string XML_ATTRIBUTE_NAME_IS_KEY {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NAME_IS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string XML_ATTRIBUTE_NAME_IS_NAME {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NAME_IS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serializeAs.
        /// </summary>
        internal static string XML_ATTRIBUTE_NAME_IS_SERIALIZEAS {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NAME_IS_SERIALIZEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string XML_ATTRIBUTE_NAME_IS_VALUE {
            get {
                return ResourceManager.GetString("XML_ATTRIBUTE_NAME_IS_VALUE", resourceCulture);
            }
        }
    }
}
