//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStand.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestStand.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing the Error Stop.
        /// </summary>
        internal static string ERRMSG_ERROR_STOP_TEST {
            get {
                return ResourceManager.GetString("ERRMSG_ERROR_STOP_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: An {1} exception occurred in routine {2}{6}                         Message            = {3}{6}                         Console.CursorLeft = {4}{6}                         Console.CursorTop  = {5}.
        /// </summary>
        internal static string ERRMSG_EXCEPTION_FOR_TRACE {
            get {
                return ResourceManager.GetString("ERRMSG_EXCEPTION_FOR_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}The specified output format, {0}, is invalid, and will be ignored.{2}    The default value, {1}, will be used.{2}.
        /// </summary>
        internal static string ERRMSG_INVALID_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_OUTPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception has occurred..
        /// </summary>
        internal static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task completed successfully..
        /// </summary>
        internal static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string MSG_BEGIN {
            get {
                return ResourceManager.GetString("MSG_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Overload {0}: .
        /// </summary>
        internal static string MSG_CASE {
            get {
                return ResourceManager.GetString("MSG_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string MSG_END {
            get {
                return ResourceManager.GetString("MSG_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}Error reporting test {0} of {1} {2}{3}.
        /// </summary>
        internal static string MSG_ERROR_REPORTING_TEST {
            get {
                return ResourceManager.GetString("MSG_ERROR_REPORTING_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the default.
        /// </summary>
        internal static string MSG_EXAMPLE_DEFAULT_COLOR {
            get {
                return ResourceManager.GetString("MSG_EXAMPLE_DEFAULT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error message appears in {0} text on {1} background..
        /// </summary>
        internal static string MSG_EXAMPLE_ERROR {
            get {
                return ResourceManager.GetString("MSG_EXAMPLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object arg0: object arg0 = {0}.
        /// </summary>
        internal static string MSG_FORMAT_13 {
            get {
                return ResourceManager.GetString("MSG_FORMAT_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to params object [ ] arg: params object [ ] arg = {0}.
        /// </summary>
        internal static string MSG_FORMAT_14 {
            get {
                return ResourceManager.GetString("MSG_FORMAT_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object arg0, object arg1: object arg0 = {0}, object arg1 = {1}.
        /// </summary>
        internal static string MSG_FORMAT_16 {
            get {
                return ResourceManager.GetString("MSG_FORMAT_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object arg0 = {0}, object arg1 = {1}, object arg2 = {2}.
        /// </summary>
        internal static string MSG_FORMAT_17 {
            get {
                return ResourceManager.GetString("MSG_FORMAT_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object arg0 = {0}, object arg1 = {1}, object arg2 = {2}, object arg3 = {3}.
        /// </summary>
        internal static string MSG_FORMAT_18 {
            get {
                return ResourceManager.GetString("MSG_FORMAT_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each of the next four screens displays all 18 overloads of a method.{0}The program pauses to allow you to capture each screen.{0}Press the Enter key when you are ready to see the first screen..
        /// </summary>
        internal static string MSG_PREPARE_CAMERA {
            get {
                return ResourceManager.GetString("MSG_PREPARE_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture this screen, then press the ENTER key..
        /// </summary>
        internal static string MSG_PROMPT_FOR_PICTURE {
            get {
                return ResourceManager.GetString("MSG_PROMPT_FOR_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Press the ENTER key to display the next example..
        /// </summary>
        internal static string MSG_SHOW_NEXT_EXAMPLE {
            get {
                return ResourceManager.GetString("MSG_SHOW_NEXT_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Exercising the Timed Exit action of the ConsoleAppStateManager.ErrorExit method.{0}.
        /// </summary>
        internal static string MSG_TIMED_ERROR_TEST {
            get {
                return ResourceManager.GetString("MSG_TIMED_ERROR_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start the test in earnest, press the RETURN key..
        /// </summary>
        internal static string MSG_TIMED_STOP_PROMPT {
            get {
                return ResourceManager.GetString("MSG_TIMED_STOP_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Exercising the Timed NormalExitAction of the ConsoleAppStateManager.NormalExit method.{0}.
        /// </summary>
        internal static string MSG_TIMED_STOP_TEST {
            get {
                return ResourceManager.GetString("MSG_TIMED_STOP_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Instance MessageInColor.Write() Tests {0}{1}.
        /// </summary>
        internal static string MSG_WRITE_IN_COLOR_TESTS {
            get {
                return ResourceManager.GetString("MSG_WRITE_IN_COLOR_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Static MessageInColor.RGBWrite() Tests {0}{1}.
        /// </summary>
        internal static string MSG_WRITE_TESTS {
            get {
                return ResourceManager.GetString("MSG_WRITE_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Instance MessageInColor.WriteLine() Tests {0}{1}.
        /// </summary>
        internal static string MSG_WRITELINE_IN_COLOR_TESTS {
            get {
                return ResourceManager.GetString("MSG_WRITELINE_IN_COLOR_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Static MessageInColor.RGBWriteLine() Tests {0}{1}.
        /// </summary>
        internal static string MSG_WRITELINE_TESTS {
            get {
                return ResourceManager.GetString("MSG_WRITELINE_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puintWaitSeconds,pstrCountdownWaitingFor,pclrTextColor,pclrTextBackgroundColor,penmInterruptCriterion.
        /// </summary>
        internal static string TIMED_WAIT_TEST_CASE_INFO {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_CASE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pstrRecord.
        /// </summary>
        internal static string TIMED_WAIT_TEST_CTOR_ARGNAME {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_CTOR_ARGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR: There are too many fields in the label template.{2}Template String = {0}{3}First Extra Label = {1}{3}Offset of First Extra Label = {2}.
        /// </summary>
        internal static string TIMED_WAIT_TEST_CTOR_ERROR_1 {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_CTOR_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR: The position of label {0} is undefined in template string {1}..
        /// </summary>
        internal static string TIMED_WAIT_TEST_CTOR_ERROR_2 {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_CTOR_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is invalid.{3}Contents of string   = {0}{3}Required Field Count = {1}{3}Actual Field Count   = {2}.
        /// </summary>
        internal static string TIMED_WAIT_TEST_CTOR_ERROR_3 {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_CTOR_ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	.
        /// </summary>
        internal static string TIMED_WAIT_TEST_DELIMITER {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_DELIMITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label row is invalid.{1}Label Row              = {0}.
        /// </summary>
        internal static string TIMED_WAIT_TEST_LABEL_TESTER_ERROR_4A {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_LABEL_TESTER_ERROR_4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Invalid Field Position = {0}{2}Invalid Field Value    = {1}.
        /// </summary>
        internal static string TIMED_WAIT_TEST_LABEL_TESTER_ERROR_4B {
            get {
                return ResourceManager.GetString("TIMED_WAIT_TEST_LABEL_TESTER_ERROR_4B", resourceCulture);
            }
        }
    }
}
